Fixing Issue #360
StanfordVL/OmniGibson pull request #364
Opened 2024-01-08 23:40 UTC by goldenJester

2024-01-09 00:03 UTC, cgokmen requested changes
Also update the PR title to explain what it does (e.g. replace timestep parameters with frequency to improve readability and robustness). Add the link to #360 using the "development" item on the right-side menu.

2024-01-09 00:03 UTC, cgokmen commented on omnigibson/configs/fetch_behavior.yaml
> +  physics_frequency: 60                 # (int): physics frequency (1 / physics_frequency for physx)
Typo in comment: this is actually 1 / physics timestep

2024-01-09 00:03 UTC, cgokmen commented on omnigibson/configs/tiago_primitives.yaml
> +  physics_frequency: 60                 # (int): physics frequency (1 / physics_frequency for physx)
Typo in comment: this is actually 1 / physics timestep

2024-01-09 00:03 UTC, cgokmen commented on omnigibson/configs/turtlebot_nav.yaml
> +  physics_frequency: 60                 # (int): physics frequency (1 / physics_frequency for physx)
Typo in comment: this is actually 1 / physics timestep

2024-01-10 20:36 UTC, cgokmen approved these changes

2024-01-13 00:33 UTC, ChengshuLi approved these changes

2024-01-13 00:33 UTC, ChengshuLi commented on omnigibson/envs/env_base.py
> +        og.sim.set_simulation_dt(physics_dt=(1 / self.physics_frequency), rendering_dt=(1 / self.action_frequency))
should we in general do `1.0 / frequency` to be 100% safe? I know probably no one will use this old a version of python...

2024-01-18 22:18 UTC, merged